export const ADD_LOG_ENTRY = 'ADD_LOG_ENTRY';
export const DELETE_LOG_ENTRY = 'DELETE_LOG_ENTRY';
export const EDIT_LOG_ENTRY = 'EDIT_LOG_ENTRY';
export const CLEAR_LOG_ENTRIES = 'CLEAR_LOG_ENTRIES';
export const SYNC_LOG_ENTRY = 'SYNC_LOG_ENTRY';
export const RECEIVE_LOG_ENTRIES = 'RECEIVE_LOG_ENTRIES';
export const UPDATE_SERVING = 'UPDATE_SERVING';

export const ADD_FOOD = 'ADD_FOOD';
export const CLEAR_FOODS = 'CLEAR_FOODS';
export const RECEIVE_FOODS = 'RECEIVE_FOODS';
export const FOOD_REQUEST = 'FOOD_REQUEST';
export const FOOD_SUCCESS = 'FOOD_SUCCESS';
export const FOOD_FAILURE = 'FOOD_FAILURE';
export const FOOD_COMPLETE = 'FOOD_COMPLETE';

export const SEARCH_RESULTS_REQUEST = 'SEARCH_RESULTS_REQUEST';
export const SEARCH_RESULTS_SUCCESS = 'SEARCH_RESULTS_SUCCESS';
export const SEARCH_RESULTS_FAILURE = 'SEARCH_RESULTS_FAILURE';
export const SEARCH_RESULTS_COMPLETE = 'SEARCH_RESULTS_COMPLETE';
export const CLEAR_SEARCH_RESULTS = 'CLEAR_SEARCH_RESULTS';

export const RESET_ERROR_MESSAGE = 'RESET_ERROR_MESSAGE';
export const TOGGLE_SHOW_ERROR = 'TOGGLE_SHOW_ERROR';

export const FIREBASE_SYNC = 'FIREBASE_SYNC';
export const ROLLBACK = 'ROLLBACK';

export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';

export const NAVIGATE = 'NAVIGATE';
